name: Vite Build and Deploy

on:
  push:
    branches: [ master ]  # 监听 master 分支的推送事件

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 环境
    
    steps:
    # 步骤 1：检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 步骤 2：设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # 推荐使用 LTS 版本
        cache: 'npm'        # 缓存 npm 依赖加速构建
    
    # 步骤 3：安装依赖
    - name: Install dependencies
      run: npm install
    
    # 步骤 4：构建 Vite 项目
    - name: Build with Vite
      run: npm run build   # 默认生成到 dist 目录
    
    # 步骤 5：部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的认证令牌
        publish_dir: ./dist                        # Vite 默认输出目录
        destination_dir: .                         # 部署到 gh-pages 根目录
        keep_files: false                          # 不保留旧文件